version: '3.8'

services:
  guestbook-api:
    build: .
    container_name: guestbook-api
    ports:
      - "8080:80"
    volumes:
      # Mount data directory for persistence
      - ./data:/var/www/html/data
    environment:
      - PHP_MEMORY_LIMIT=128M
      - PHP_MAX_EXECUTION_TIME=30
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/guestbook.php"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

networks:
  default:
    name: guestbook-api-network